version: "3.7"

services:
  salt-master-debian:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-12-master
    container_name: salt-master-debian
    hostname: salt.master.debian
    volumes:
      - ..:/workspace:rw
      - ./master.d:/etc/salt/master.d:ro
      - ../salt:/srv/salt:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - salt-playground

  salt-minion-debian:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Debian-12-minion
    image: salt-minion-debian
    container_name: salt-minion-debian
    hostname: debian.salt.minion
    volumes:
      - ./minion.d/debian/:/etc/salt/minion.d/:ro
    networks:
      - salt-playground

  # salt-minion-ubuntu:
  #   build:
  #     context: ./Dockerfiles
  #     dockerfile: Dockerfile-Ubuntu-2204
  #   image: salt-minion-ubuntu
  #   container_name: salt-minion-ubuntu
  #   hostname: ubuntu.salt.minion
  #   volumes:
  #     - ../minion.d/ubuntu/:/etc/salt/minion.d/:ro
  #   networks:
  #     - salt-playground

  salt-minion-rocky:
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile-Rocky-8
    image: salt-minion-rocky
    container_name: salt-minion-rocky
    hostname: rocky.salt.minion
    volumes:
      - ../minion.d/rocky/:/etc/salt/minion.d/:ro
    networks:
      - salt-playground


networks:
  salt-playground:
