FROM local/debian-base
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y --no-install-recommends \
    salt-minion
# RUN mkdir -p /run/sshd && ssh-keygen -A
# CMD ["/usr/sbin/sshd", "-D"]
ENTRYPOINT [ "salt-minion", "-l", "debug" ]
