FROM local/debian-base
RUN apt update && \
    export DEBIAN_FRONTEND=noninteractive && \
    apt install -y --no-install-recommends \
    lsb-release \
    ifupdown \
    salt-master \
    bash-completion
# RUN mkdir -p /run/sshd && ssh-keygen -A
# CMD ["/usr/sbin/sshd", "-D"]
ENTRYPOINT [ "salt-master", "-l", "debug" ]
